name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 레포지토리
        uses: actions/checkout@v4

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: 의존성 설치
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} 
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            cd /home/ubuntu/drf-ci-cd
            git pull origin main
            
            cd /home/ubuntu/drf-ci-cd/WebCAM-Django
            
            echo "SECRET_KEY=\"${{ secrets.SECRET_KEY }}\"" > .env
            echo "DEBUG='${{ secrets.DEBUG }}'" > .env

            source venv/bin/activate
            pip install -r requirements.txt
            
            pyhton3 manage.py collectstatic
            
            sudo systemctl restart site.service
