name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃 레포지토리
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: 의존성 설치
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            set -e
            cd /home/ubuntu/app/drf-ci-cd
            git add .
            git commit -m "dude king"
            git pull --rebase origin main
            
            cd /home/ubuntu/app/drf-ci-cd/pp_enter_be
            mkdir static
            mkdir staticfiles
            
            echo "SECRET_KEY=\"${{ secrets.SECRET_KEY }}\"" > .env
            echo "DEBUG='${{ secrets.DEBUG }}'" > .env

            source ../venv/bin/activate
            pip install -r ../requirements.txt

            python3 manage.py collectstatic --noinput
            python3 manage.py makemigrations
            python3 manage.py migrate --run-syncdb
            
            sudo systemctl restart site.service
          
